

CREATE OR REPLACE TABLE Cases_Over_Location (
    LOCATION VARCHAR(256),
    NEW_CASES NUMBER(38,0),
    ACTIVE_CASES NUMBER(38,0),
    NEW_DEATHS NUMBER(38,0),
    NEW_RECOVERD NUMBER(38,0),
    TOTAL_CASES NUMBER(38,0),
    TOTAL_DEATHS NUMBER(38,0),
    TOTAL_RECOVERED NUMBER(38,0),
    "DATE" VARCHAR(256)
);

INSERT INTO Cases_Over_Location (LOCATION, NEW_CASES,ACTIVE_CASES,NEW_DEATHS,NEW_RECOVERD,TOTAL_CASES,TOTAL_DEATHS,TOTAL_RECOVERED, "DATE") 
SELECT LOCATION,NEW_CASES,NEW_ACTIVE_CASES,NEW_DEATHS,NEW_RECOVERED,TOTAL_CASES, TOTAL_DEATHS,TOTAL_RECOVERED,"DATE"
FROM "FIVETRAN_INTERVIEW_DB"."GOOGLE_SHEETS_YR"."FIVETRAN_INTERVIEW_DB_YR" WHERE "DATE" != 'Date';
