CREATE OR REPLACE TABLE DEATHS_PER_MONTH (
    TOTAL_DEATHS NUMBER(38,0),
    LOCATION VARCHAR(256),
    "MONTH" VARCHAR(256),
    "YEAR" VARCHAR(4)
);

INSERT INTO DEATHS_PER_MONTH (TOTAL_DEATHS, LOCATION,"MONTH","YEAR")
SELECT SUM(TOTAL_DEATHS), LOCATION,"MONTH","YEAR" FROM (SELECT TOTAL_DEATHS, LOCATION,
MONTHNAME(to_date("DATE", 'MM/DD/YYYY')) as "MONTH", YEAR(to_date("DATE", 'MM/DD/YYYY')) as "YEAR" FROM "FIVETRAN_INTERVIEW_DB"."GOOGLE_SHEETS"."COVID_19_INDONESIA_YASHRAJ_RAJPUT" WHERE "DATE" != 'Date')
GROUP BY LOCATION, "MONTH","YEAR";